# Generated by Django 3.2.25 on 2026-06-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('rollno', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('address', models.TextField()),
                ('course', models.CharField(choices=[('pfs', 'python full stack'), ('jfs', 'java full stack'), ('mern', 'mern full stack'), ('ai/ml', 'artificial intelligence machine learning')], max_length=100)),
            ],
        ),
    ]
